# Brightway2 seminar
Chris Mutel ([PSI](https://www.psi.ch/)), Pascal Lesage ([CIRAIG](http://www.ciraig.org/en/))

## Day 1, afternoon
### Session on uncertainty in Brightway

### Learning objectives  
  - Learn how uncertainty is represented in exchanges  
  - Learn how to carry out a MonteCarloLCA  

Standard inputs

In [1]:
import brightway2 as bw
import numpy as np

Open the seminar project:

In [2]:
bw.projects.set_current('bw2_seminar_2017')

### 1) Uncertainty information in Brightway exchanges

Uncertainty is stored at the level of the exchanges.  

**Sample exchange from ecoinvent v3.3 (`lognormal`**)   
Let's look at a random exchange from ecoinvent 3.3, from which we removed some fields that were not necessary for the purpose of discussing uncertainty :

In [3]:
some_exc_from_ecoinvent = {'name': 'ethylene, average',
                           'type': 'technosphere',
                           'amount': 0.23244,
                           'unit': 'kilogram',
                           'input': ('ecoinvent 3.3 cutoff', '14db59eea64e46a1e8332973f714a3ef'),
                           'output': ('ecoinvent 3.3 cutoff', 'df875d1e65cd48bc1ac69b960e172e85'),
                           'uncertainty type': 2,
                           'loc': -1.459123151775232,
                           'scale without pedigree': 0.1414213562373095,
                           'scale': 0.2,
                           'pedigree': {
                               'completeness': 5,
                               'further technological correlation': 1,
                               'geographical correlation': 5,
                               'reliability': 4,
                               'temporal correlation': 3
                           }
                          }

In this *specific* case, the *necessary* uncertainty of the exchange are described in the following fields:  
  - **'uncertainty type'** : type of probability distribution function that the exchange follows. In this case, the exchange has an uncertainty type = 2, indicating it is a `lognormal`  distribution.  
  - **'loc', 'scale'**: parameters of the lognormal distribution function, which are respectively the mean $\mu$ and the standard deviation $\sigma$ of the underlying normal distribution (more on this later).  
  
Other probability distributions functions (e.g. normal, triangular, etc.) can also be modelled, and will each have their own specific paramters (more on this later). 

Some *additional* uncertainty related information ('scale without pedigree', 'pedigree') are also there, but are not directly used in the calculation of the uncertainty. They are also specific to ecoinvent. 

Uncertainty in Brightway is dealt with using a Python package called `stats_arrays` (see [here](http://stats-arrays.readthedocs.io/en/latest/)), developed by Chris Mutel in the context of the development of Brightway but applicable to any stochastic model in Python. Let's import it. 

In [4]:
import stats_arrays

Before delving into the details of ` stats_arrays`, let's have a quick look at the uncertainty information above. 
As a reminder:   
  - a random variable $X$ is a lognormal if its natural logarithm $ln(X)$ is normally distributed  
  - the natural logarithm of the *median* of the lognormal distribution is equal to the median (=mean) of the underlying distribution  

Taking the deterministic amount `amount` to be the median, we should have `loc` = `ln('amount')`. 

In [5]:
some_exc_from_ecoinvent['loc'] == np.log(some_exc_from_ecoinvent['amount'])

True

The link between the geometric standard deviation ($GSD$) of $X$ and the standard deviation of $ln(X)$ ($/mu$) is:  $GSD=e^{\mu}$. The $GSD^2$ og the sample exchange above is therefore:

In [6]:
GSD2 = np.exp(some_exc_from_ecoinvent['scale'])**2
GSD2

1.4918246976412703

Approximately 95% of the values for the lognormally distributed parameter $X$ are between $median/GSD^2$ and $median*GSD^2$. In the example:  

In [7]:
print("Approx. 95% of the values are in the range [{}, {}]".format(some_exc_from_ecoinvent['amount']/GSD2, some_exc_from_ecoinvent['amount']*GSD2))

Approx. 95% of the values are in the range [0.155809191500524, 0.34675973271973687]


In a Monte Carlo simulation, we would want to sample a large number of values for many random variables and recalculate results using these randomly sampled values. This is where `stats_arrays` comes in.  

The `stats_arrays` methods requires parameter arrays for the random variables. These parameter arrays contain exactly seven paramters per random variable, and are stored as a Numpy structured array. These seven parameters are:  
 - 'loc' (first shape parameter of the distribution, related to the central tendency  
 - 'scale' (second shape parameter, related to the dispersion of the paramter)  
 - 'shape' (third shape parameter, related to the dispersion's skewness)  
 - 'minimum' (lower limit to the values that can be sampled. This can be a core parameter of the distribution (e.g. for the uniform distribution) of an optional parameter (e.g. for normal distributions for which negatove values are excluded).  
 - 'maximum' (upper limit to the values that can be sampled - see 'minimum'.  
 - 'negative' (an indication of whether the random variable is negative. useful for generating e.g. "negative lognormals".
 - 'uncertainty_type' Type of uncertainty (normal, lognormal, triangular, etc.)  

The following table, taken from [here](http://stats-arrays.readthedocs.io/en/latest/), that states which paramters are required, which are optional and which are not relevant for the distribution functions explicitly modeled now in `stats_arrays`  
<img src="images/stats_arrays_table.JPG">

One can create a stats array using the class method `stats_arrays.UncertaintyBase.from_dicts' 

In [8]:
# Creating a stats array for three random variables. 
my_uncertain_variables = stats_arrays.UncertaintyBase.from_dicts(
    {'loc': some_exc_from_ecoinvent['loc'], 
     'scale': some_exc_from_ecoinvent['scale'], 
     'uncertainty_type': some_exc_from_ecoinvent['uncertainty type']},
    {'loc': 2, 'scale': 0.5, 'uncertainty_type': stats_arrays.NormalUncertainty.id},
    {'loc': 1.5, 'minimum': 0, 'maximum': 10, 'uncertainty_type': stats_arrays.TriangularUncertainty.id}
)
my_uncertain_variables

array([(-1.459123151775232, 0.2, nan, nan, nan, False, 2),
       (2.0, 0.5, nan, nan, nan, False, 3),
       (1.5, nan, nan, 0.0, 10.0, False, 5)], 
      dtype=[('loc', '<f8'), ('scale', '<f8'), ('shape', '<f8'), ('minimum', '<f8'), ('maximum', '<f8'), ('negative', '?'), ('uncertainty_type', 'u1')])

One can then use the `stats_arrays.MCRandomNumberGenerator` to generate samples for the differnt variables, which is a generator for which we can use the `next` command:

In [9]:
my_rng = stats_arrays.MCRandomNumberGenerator(my_uncertain_variables)

In [10]:
# Using `next`:
next(my_rng)

array([ 0.14446922,  3.0110584 ,  2.47628226])

In [14]:
# Using `next` in a loop:
np.array([my_rng.next() for _ in range(10)])

array([[ 0.2013928 ,  1.77508965,  1.45560065],
       [ 0.26307623,  1.59809165,  2.64335433],
       [ 0.21434987,  2.59653097,  0.36204553],
       [ 0.20059211,  2.24207089,  4.27351492],
       [ 0.27247172,  1.32120266,  6.42717852],
       [ 0.2223453 ,  2.26313795,  4.02522667],
       [ 0.27595694,  2.11118213,  2.3128555 ],
       [ 0.17926146,  2.29801956,  5.13987679],
       [ 0.2030141 ,  2.59825691,  1.79198025],
       [ 0.2030141 ,  2.59825691,  1.79198025]])

## 2) Monte Carlo calculations in Brightway

### General syntax

In [15]:
random_act = bw.Database('ecoinvent 2.2').random()
random_act

'disposal, polystyrene, 0.2% water, to sanitary landfill' (kilogram, CH, ['waste management', 'sanitary landfill'])

In [16]:
myFirstMonteCarlo = bw.MonteCarloLCA({random_act:1},  ('IPCC 2013', 'climate change', 'GWP 100a'))
scores = [next(myFirstMonteCarlo) for _ in range(10)]
scores

[0.2266588766364485,
 0.24330160744554438,
 0.06985443727526659,
 0.19042512526560224,
 0.12386418104725405,
 0.21290091507276002,
 0.16209711722975312,
 0.14210937537119828,
 0.08964117254743804,
 0.17755529437574913]

### How it works  
  - Matrices are built as in standard LCA (using the approach seen this morning `builder`)  
  - The `MCRandomNumberGenerator` generates new values for all paramters in the $A$ and $B$ matrices (and for characterization factors if the LCA has an LCIA component, i.e. if `MonteCarloLCA` was instantiatied with a method).  
  - For every subsequent iteration, matrices are rebuilt with new sampled values BUT same indices, cutting down on matrix building time  
  - Rather than solving the system of linear equations directly, an *iterative solver* is used. This takes as an initial guess the solution found with the paramter values from the first Monte Carlo iteration.   

### Monte Carlo using multiple impact assessment methods (no uncertainty on characterization factors)
There is presently no method in Brightway that does MonteCarlo iterationswith multiple LCIA methods. This can be annoying since the results obtained for different impact categories are correlated (they depend on some of the same paramters from the $A$ and, to a smaller extent, $B$ matrix), but this correlation is lost when you need to do Monte Carlo simulations sequentially. 
There are two obvious solutions (and probably many other, not so obvious solutions):  

**Solution 1**: One can store the $A$ and $B$ matrix values and reuse them. This is possible using the `ParameterVectorLCA` class of Monte Carlo, which generates a single array with all these parameters as well as sampled characterization factors. While not implemented, it would be possible to concatenate many such vectors (one per MonteCarlo iteration) and recalculate LCIA scores using matrices built using `ParameterVectorLCA.rebuild_all`.

**Solution 2**: If there is no uncertainy associated with the characterization factors, one can instead store characterization matrices and multiply the inventory resulting from MonteCarloLCA for each iteration.  

**Exercise**: Write a function that uses MonteCarloLCA and calculates arrays of scores for multiple impact categories. Test your function with a functional unit = {random_act:1}, list of methods = all ILCD methods (with long term emissions) and 1000 MOnte Carlo iterations.

Step 1) Create a MonteCarloLCA object with some functional unit but no method. Run `.lci` to build the $A$ and $B$ matrices (and hence fix the indices of our matrices)  
Step 2) Create a 'C_matrices' dictionary (empty for now), that will collect characterization factor matrices (C matrices). Keys will be the tuple representing the method name, and the values will be the actual matrices.  
Step 3) Write a `for` loop that iterates over a list of method names and stores the method_name:C_matrix in the dictionary. Use `switch_method` to do this.  
Once this dictionary is built:  
Step 4): Create an empty array (`np.empty`) of dimension equal to the number of methods that will be considered (rows) by the number of iterations required (columns).  
Step 5) Populate this array using a `for` loop over the number of MonteCarlo iterations required (use `next` to rebuild the $A$ and $B$ matrices). Include a nested `for` loop over the methods and multiply the characterization matrix with the inventory.  
Step 6) Take all this code and structure it in a function that takes as arguments (1) the functional unit, (2) a list of method names and (3) the number of iterations.

In [17]:
def multiImpactMonteCarloLCA(functional_unit, list_methods, iterations):
    # Step 1
    MC_lca = bw.MonteCarloLCA(functional_unit)
    MC_lca.lci()
    # Step 2
    C_matrices = {}
    # Step 3
    for method in list_methods:
        MC_lca.switch_method(method)
        C_matrices[method] = MC_lca.characterization_matrix
    # Step 4
    results = np.empty((len(list_methods), iterations))
    # Step 5
    for iteration in range(iterations):
        next(MC_lca)
        for method_index, method in enumerate(list_methods):
            results[method_index, iteration] = (C_matrices[method]*MC_lca.inventory).sum()
    return results

In [18]:
ILCD = [method for method in bw.methods if "ILCD" in str(method) and "no LT" not in str(method)]
fu = {random_act:1}
iterations = 100

In [19]:
test_results = multiImpactMonteCarloLCA(fu, ILCD, iterations)

In [20]:
test_results

array([[  8.24932399e-07,   3.56992710e-06,   5.99090789e-07, ...,
          1.86062909e-06,   1.06484555e-06,   9.01210864e-07],
       [  9.60372410e-06,   1.03202751e-05,   1.00134352e-05, ...,
          7.65655170e-06,   1.57023553e-05,   1.31992180e-05],
       [  5.06932810e-04,   4.15442109e-04,   3.89062868e-04, ...,
          3.64524547e-04,   9.00374102e-04,   7.27372829e-04],
       ..., 
       [  1.84721041e-03,   4.89652448e-04,   5.16206921e-04, ...,
          8.86926518e-04,   8.16891137e-04,   8.56551544e-04],
       [  2.44920458e-07,   9.00140326e-09,   2.95517100e-09, ...,
          7.87446771e-09,   3.77496471e-09,   4.47373615e-09],
       [  2.86973143e-04,   1.63116954e-04,   1.26046679e-04, ...,
          1.46994836e-04,   2.64839430e-04,   2.73189221e-04]])